// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn("Supabase credentials missing! Ensure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY are in .env");
}

// Partition session storage by URL path to isolate Admin and User sessions
const is_admin = () => typeof window !== 'undefined' && window.location.pathname.startsWith('/admin');
const partition_key = is_admin() ? 'adm-session-v5' : 'usr-session-v5';

export const supabase = createClient<Database>(
  SUPABASE_URL || "",
  SUPABASE_PUBLISHABLE_KEY || "",
  {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      storageKey: partition_key,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true
    }
  }
);